name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm ci 
  
      - name: build
        run: |
          npm run build

deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 1
          format: 'YYYY-MM-DD-HH-mm-ss'
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          cache-from: type=registry,ref=almarkdev/web-interface:latest
          cache-to: type=inline  
          tags: almarkdev/web-interface:${{ steps.time.outputs.time }}
